apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlist-recommender
  labels:
    app: gabrielafonseca-playlist-recommender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gabrielafonseca-playlist-recommender
  template:
    metadata:
      labels:
        app: gabrielafonseca-playlist-recommender
    spec:
      containers:
        - name: ml-container
          image: gabifonseca/ml-container:1.0
          env:
            - name: DATA_URL
              value: "https://raw.githubusercontent.com/FonsecaGabriela/TP2_CLOUD_COMPUTING/main/data/2023_spotify_ds1.csv"
        - name: frontend-container
          image: gabifonseca/frontend-container:1.0
          ports:
            - containerPort: 5000
