apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pv2-claim
  namespace: gabrielafonseca
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  
  storageClassName: default-storage-class-gabrielafonseca 
