apiVersion: v1
kind: Service
metadata:
  name: playlist-recommender-service
spec:
  selector:
    app: gabifonseca-playlist-recommender  
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 5000  
  type: ClusterIP
